# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: tidyverse_version
  displayName: Tidyverse Version
  type: string
  default: rocker/tidyverse:latest
  values:
  - rocker/tidyverse:latest
  - rocker/tidyverse:3.6.3
  - rocker/tidyverse:3.6.2
  - rocker/tidyverse:3.6.1
  - rocker/tidyverse:3.6.0
  - rocker/tidyverse:3.5.3
  - rocker/tidyverse:3.5.2
  - rocker/tidyverse:3.5.1
  - rocker/tidyverse:3.5.0
  - rocker/tidyverse:3.4.4
  - rocker/tidyverse:3.4.3
  - rocker/tidyverse:3.4.2
  - rocker/tidyverse:3.4.1
  - rocker/tidyverse:3.4.0
  - rocker/tidyverse:3.3.3
  - rocker/tidyverse:3.3.2
  - rocker/tidyverse:3.3.1

container: ${{ parameters.tidyverse_version }}

steps:

- script: sudo Rscript -e 'install.packages("huxtable"); devtools::check(cran = FALSE)'
  displayName: 'Package Check'

- script: Rscript -e 'sessionInfo()'
  displayName: 'R Version'
